export enum InjectionTokens {
  AnalyticsModule = "AnalyticsModule",
  Cache = "Cache",
  CodeHost = "CodeHost",
  Database = "Database",
  DatabaseConfig = "DatabaseConfig",
  DocProvider = "DocProvider",
  InfraRepoPorts = "InfraRepoPorts",
  Llm = "Llm",
  LlmConfig = "LlmConfig",
  Logger = "Logger",
  MetricsRegistry = "MetricsRegistry",
  OpenRouterConfig = "OpenRouterConfig",
  PipelineConfig = "PipelineConfig",
  PipelineMetrics = "PipelineMetrics",
  RateLimiter = "RateLimiter",
  RespondToComment = "RespondToComment",
  ReviewModule = "ReviewModule",
  WebhookConfig = "WebhookConfig",
}
