const MILLISECONDS_PER_SECOND = 1_000;
const SECONDS_PER_MINUTE = 60;
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE;

const MIN_CLEANUP_RETENTION_DAYS = 1;
const DEFAULT_CLEANUP_RETENTION_DAYS = 90;
const MIN_CLEANUP_TOKEN_LENGTH = 32;
const DEFAULT_PORT = 3_000;
const MIN_SHUTDOWN_TIMEOUT_MS = MILLISECONDS_PER_SECOND;
const DEFAULT_SHUTDOWN_TIMEOUT_MS = 4 * MILLISECONDS_PER_MINUTE;

const MIN_WEBHOOK_MAX_QUEUE_SIZE = 1;
const DEFAULT_WEBHOOK_MAX_QUEUE_SIZE = 150;

const DEFAULT_ARCHITECTURE_SNAPSHOT_MAX_FILE_CHARS = 8_000;
const DEFAULT_ARCHITECTURE_SNAPSHOT_MAX_LIST_FILES = 200;
const DEFAULT_ARCHITECTURE_SNAPSHOT_MAX_TOTAL_CHARS = 40_000;
const DEFAULT_COMMENT_RESPONSE_MAX_DIFF_LENGTH = 200_000;
const DEFAULT_COMMENT_RESPONSE_MAX_TOOL_ROUNDS = 3;
const DEFAULT_COMMENT_RESPONSE_PROMPT_HARD_LIMIT = 8_000;
const DEFAULT_FILE_REVIEW_MAX_DIFF_CHARACTERS = 60_000;
const DEFAULT_FINDING_THREAD_ARCHITECTURE_SNAPSHOT_MAX_TOTAL_CHARS = 12_000;
const DEFAULT_FINDING_THREAD_PROMPT_HARD_LIMIT = 12_000;
const DEFAULT_FORCE_PUSH_LINE_MATCH_TAB_WIDTH = 4;
const DEFAULT_FORCE_PUSH_LINE_WINDOW = 20;
const DEFAULT_LINE_SHIFT_DEDUP_TOLERANCE = 3;
const DEFAULT_REVIEW_BASELINE_POLL_MS = 400;
const DEFAULT_REVIEW_BASELINE_READY_TIMEOUT_MS = 15 * MILLISECONDS_PER_MINUTE;
const DEFAULT_REVIEW_CROSS_FILE_PROMPT_HARD_LIMIT = 12_000;
const DEFAULT_REVIEW_FILE_PROMPT_HARD_LIMIT = 10_000;
const DEFAULT_REVIEW_TRIAGE_PROMPT_HARD_LIMIT = 5_000;
const DEFAULT_RUN_STUCK_AFTER_MS = 30 * MILLISECONDS_PER_MINUTE;
const DEFAULT_THREAD_PRIOR_FINDINGS_MAX_CHARS = 4_000;

export {
  DEFAULT_ARCHITECTURE_SNAPSHOT_MAX_FILE_CHARS,
  DEFAULT_ARCHITECTURE_SNAPSHOT_MAX_LIST_FILES,
  DEFAULT_ARCHITECTURE_SNAPSHOT_MAX_TOTAL_CHARS,
  DEFAULT_CLEANUP_RETENTION_DAYS,
  DEFAULT_COMMENT_RESPONSE_MAX_DIFF_LENGTH,
  DEFAULT_COMMENT_RESPONSE_MAX_TOOL_ROUNDS,
  DEFAULT_COMMENT_RESPONSE_PROMPT_HARD_LIMIT,
  DEFAULT_FILE_REVIEW_MAX_DIFF_CHARACTERS,
  DEFAULT_FINDING_THREAD_ARCHITECTURE_SNAPSHOT_MAX_TOTAL_CHARS,
  DEFAULT_FINDING_THREAD_PROMPT_HARD_LIMIT,
  DEFAULT_FORCE_PUSH_LINE_MATCH_TAB_WIDTH,
  DEFAULT_FORCE_PUSH_LINE_WINDOW,
  DEFAULT_LINE_SHIFT_DEDUP_TOLERANCE,
  DEFAULT_PORT,
  DEFAULT_REVIEW_BASELINE_POLL_MS,
  DEFAULT_REVIEW_BASELINE_READY_TIMEOUT_MS,
  DEFAULT_REVIEW_CROSS_FILE_PROMPT_HARD_LIMIT,
  DEFAULT_REVIEW_FILE_PROMPT_HARD_LIMIT,
  DEFAULT_REVIEW_TRIAGE_PROMPT_HARD_LIMIT,
  DEFAULT_RUN_STUCK_AFTER_MS,
  DEFAULT_SHUTDOWN_TIMEOUT_MS,
  DEFAULT_THREAD_PRIOR_FINDINGS_MAX_CHARS,
  DEFAULT_WEBHOOK_MAX_QUEUE_SIZE,
  MIN_CLEANUP_RETENTION_DAYS,
  MIN_CLEANUP_TOKEN_LENGTH,
  MIN_SHUTDOWN_TIMEOUT_MS,
  MIN_WEBHOOK_MAX_QUEUE_SIZE,
};
